@SchoolApi_HostAddress = http://localhost:5009

GET {{SchoolApi_HostAddress}}/students/
Accept: application/json

###

GET http://localhost:5009/Students/cd7a0ca1-e914-4a35-abfa-4f05c94c3bf0

###
POST http://localhost:5009/Students
js